[project]
name = "cca-project"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "docker>=7.1.0",
    "matplotlib>=3.10.1",
    "pandas>=2.2.3",
    "paramiko>=3.5.1",
    "psutil>=7.0.0",
    "seaborn>=0.13.2",
]
