apiVersion: batch/v1
kind: Job
metadata:
  labels:
    name: parsec-vips
  name: parsec-vips
spec:
  template:
    spec:
      containers:
      - args:
        - -c
        - ./run -a run -S parsec -p vips -i native -n 8
        command:
        - /bin/sh
        image: anakli/cca:parsec_vips
        imagePullPolicy: Always
        name: parsec-vips
      nodeSelector:
        cca-project-nodetype: parsec
      restartPolicy: Never
