apiVersion: batch/v1
kind: Job
metadata:
  labels:
    name: parsec-freqmine
  name: parsec-freqmine
spec:
  template:
    spec:
      containers:
      - args:
        - -c
        - ./run -a run -S parsec -p freqmine -i native -n 8
        command:
        - /bin/sh
        image: anakli/cca:parsec_freqmine
        imagePullPolicy: Always
        name: parsec-freqmine
      nodeSelector:
        cca-project-nodetype: parsec
      restartPolicy: Never
