apiVersion: batch/v1
kind: Job
metadata:
  labels:
    name: parsec-ferret
  name: parsec-ferret
spec:
  template:
    spec:
      containers:
      - args:
        - -c
        - ./run -a run -S parsec -p ferret -i native -n 4
        command:
        - /bin/sh
        image: anakli/cca:parsec_ferret
        imagePullPolicy: Always
        name: parsec-ferret
      nodeSelector:
        cca-project-nodetype: node-d-4core
      restartPolicy: Never
