apiVersion: batch/v1
kind: Job
metadata:
  labels:
    name: parsec-blackscholes
  name: parsec-blackscholes
spec:
  template:
    spec:
      containers:
      - args:
        - -c
        - ./run -a run -S parsec -p blackscholes -i native -n 2
        command:
        - /bin/sh
        image: anakli/cca:parsec_blackscholes
        imagePullPolicy: Always
        name: parsec-blackscholes
      nodeSelector:
        cca-project-nodetype: node-b-2core
      restartPolicy: Never
